### ISSUE TITLE
does not work in wasm

### ISSUE THREAD

**Issue by extrawurst** [NobodyXu/generic-global-variables#1]
would be helpful if we had a feature enabling `parking_lot/wasm-bindgen`

see https://github.com/libp2p/rust-libp2p/issues/2143

**Comment by NobodyXu** [comment]
If `std::sync::Mutex` works on wasm, then maybe I can add a new feature for `parking_lot`, making it optional?

**Comment by extrawurst** [comment]
no its really just about using the right parking_lot feature flag: https://github.com/extrawurst/bevy_extern_events/commit/e46f9ac912510d62b0adb0d50932a322f11c351f

**Comment by NobodyXu** [comment]
I didn't find the feature "wasm-bindgen" on parking_lot https://github.com/Amanieu/parking_lot/blob/master/Cargo.toml which is strange because bevy also uses it...

**Comment by extrawurst** [comment]
Ha it was removed in 0.12. so my PR might have actually fixed it 😂

see https://github.com/Amanieu/parking_lot/commit/6e355244a3ff21b203471cec13dd306ad5fd2e70

**Comment by NobodyXu** [comment]
I will publish a new release tonight then.

**Comment by NobodyXu** [comment]
Released v0.1.2
